---
title: "MAGMA_Files_Public: README"
author: "<h4> Brian M. Schilder</h4>"
date: "<h4>Updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  github_document 
editor_options: 
  chunk_output_type: inline
---

GWAS gene set files generated by MAGMA for use in downstream analyses (e.g. [`MAGMA_celltyping`](https://github.com/neurogenomics/MAGMA_Celltyping)).


## Usage

These files can be imported using `MAGMA_celltyping::import_magma`.

```{r, eval=FALSE}
if(!require(remotes)) install.packages("remotes")
if(!require(MAGMA.celltyping)) remotes::install_github("neurogenomics/MAGMA_celltyping@bschilder_dev") 
```

```{r, eval=FALSE}
#### Search the MAGMA_Files_Public database's metadata ####
meta <- MAGMA.Celltyping::magma_files_metadata
#### Import MAGMA files ####
magma_dirs <- MAGMA.Celltyping::import_magma_files(ids = c("ieu-a-298"))
```

## [Metadata report](https://neurogenomics.github.io/MAGMA_Files_Public/vignettes/metadata_report.html) 

<hr>

## Session Info

<details>

```{r}
utils::sessionInfo()
```

</details>

<br>
