#PBS -l walltime=36:00:00
#PBS -l select=1:ncpus=4:mem=50gb -q med-bio
#PBS -J 1-23
module load anaconda3/personal
source activate bioc
cd $PBS_O_WORKDIR


#read line from tab-delimited metadata file
repo=/rds/general/project/neurogenomics-lab/live/Data/MAGMA_Files_Public
file=/rds/general/project/neurogenomics-lab/live//Data/MAGMA_Files_Public/code/gwas_meta.tsv

#identify which row to use in metadata
batch=0
row=$((batch*50+PBS_ARRAY_INDEX))

#extract relevant columns from a specific row
id=`tail -n+2 $file | awk -F'\t' -v row=$row '{if(NR==row)print $1}'`
trait=`tail -n+2 $file | awk -F'\t' -v row=$row '{if(NR==row)print $2}'`
Rscript /rds/general/project/neurogenomics-lab/live/Data/MAGMA_Files_Public/code/mungesumstats.R -i $id -n 4
